#!/bin/bash
# LGSM fn_check_systemdir function
# Original Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 210115

if [ ! -e "${systemdir}" ]; then
	fn_printfailnl "Cannot access ${systemdir}: No such directory"
	exit
fi