#!/bin/bash
# LGSM fn_getopt function
# Modified by : Kugane
# Original Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 200615

# Description: getopt arguments.

fn_getopt_generic(){
case "$getopt" in
	start)
		fn_start;;
	stop)
		fn_stop;;
	restart)
		fn_restart;;
	debug)
		fn_debug;;
	update)
		fn_update_check;;
	force-update)
		forceupdate=1;
		fn_update_check;;
	update-functions)
		fn_update_functions;;
	validate)
		fn_validate;;
	monitor)
		fn_monitor;;
	email-test)
		fn_email_test;;
	details)
		fn_details;;
	backup)
		fn_backup;;
	install)
		fn_install;;
	auto-install)
		fn_autoinstall;;
	depsdetect)
		fn_deps_detect;;		
	*)
	echo "Usage: $0 {start|stop|restart|debug|update|force-update|update-functions|validate|monitor|email-test|details|backup|install|auto-install}"
	exit 1;;
esac
exit
}
	fn_getopt_generic
fi