#!/bin/bash
# LGSM fn_install_config function
# Modified by : Kugane
# Original Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 210615

fn_arma3config(){
mkdir -pv "${servercfgdir}"
mkdir -pv "${rcondir}"
mv -v exlgsm-default.server.cfg "${servercfgfullpath}"
mv -v exlgsm-default.network.cfg "${networkcfgfullpath}"
mv -v beserver.cfg "${systemdir}"/battleye
mv -v config.php "${rcondir}"
mv -v resinf.php "${rcondir}"
mv -v lock.php "${rcondir}"
mv -v restart30min.php "${rcondir}"
mv -v restart15min.php "${rcondir}"
mv -v restart10min.php "${rcondir}"
mv -v restart5min.php "${rcondir}"
mv -v restart3min.php "${rcondir}"
mv -v restart2min.php "${rcondir}"
mv -v update30min.php "${rcondir}"
mv -v update15min.php "${rcondir}"
mv -v update10min.php "${rcondir}"
mv -v update5min.php "${rcondir}"
mv -v update3min.php "${rcondir}"
mv -v update2min.php "${rcondir}"
mv -v cronjobs.txt "${systemdir}"

sleep 1
echo ""
}


echo ""
echo "Creating Configs"
echo "================================="
sleep 1
if [ "${gamename}" == "ARMA 3" ]; then
	cd "${systemdir}"
fi
	#statements
if [ "${gamename}" == "ARMA 3" ]; then
	echo -e "downloading exlgsm-default.server.cfg & exlgsm-default.network.cfg...\c"
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/cfg/exlgsm-default.network.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/cfg/exlgsm-default.server.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/cfg/beserver.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/config.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/resinf.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/lock.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart30min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart15min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart10min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart5min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart3min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart2min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update30min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update15min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update10min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update5min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update3min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update2min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/cronjobs.txt 2>&1 | grep -F HTTP | cut -c45- | uniq
	sleep 1
	fn_arma3config
fi