#!/bin/bash
# LGSM fn_install_config function
# Modified by : Kugane
# Original Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 210615

fn_arma3config(){
echo -e "Creating config dir & rcon dir"
mkdir -pv "${servercfgdir}"
mkdir -pv "${rcondir}"
echo -e "Move config files"
mv -u exlgsm-default.server.cfg "${servercfgfullpath}"
mv -u exlgsm-default.network.cfg "${networkcfgfullpath}"
echo -e "Move beserver.cfg"
mv -u beserver.cfg "${systemdir}"/battleye
echo -e "Move rcon files"
mv -u config.php "${rcondir}"
mv -u resinf.php "${rcondir}"
mv -u lock.php "${rcondir}"
mv -u restart30min.php "${rcondir}"
mv -u restart15min.php "${rcondir}"
mv -u restart10min.php "${rcondir}"
mv -u restart5min.php "${rcondir}"
mv -u restart3min.php "${rcondir}"
mv -u restart2min.php "${rcondir}"
mv -u update30min.php "${rcondir}"
mv -u update15min.php "${rcondir}"
mv -u update10min.php "${rcondir}"
mv -u update5min.php "${rcondir}"
mv -u update3min.php "${rcondir}"
mv -u update2min.php "${rcondir}"
sleep 1
echo ""
}


echo ""
echo "Creating Configs"
echo "================================="
sleep 1
if [ "${gamename}" == "ARMA 3" ]; then
	cd "${systemdir}"
fi
	#statements
if [ "${gamename}" == "ARMA 3" ]; then
	echo -e "downloading exlgsm-default.server.cfg & exlgsm-default.network.cfg...\c"
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/cfg/exlgsm-default.network.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/cfg/exlgsm-default.server.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
	echo -e "downloading beserver.cfg...\c"
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/cfg/beserver.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
	echo -e "downloading rcon scripts...\c"
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/config.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/resinf.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/lock.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart30min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart15min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart10min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart5min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart3min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/restart2min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update30min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update15min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update10min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update5min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -Nq /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update3min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/rcon/update2min.php 2>&1 | grep -F HTTP | cut -c45- | uniq
	echo -e "downloading cronjob example...\c"
	wget -N /dev/null https://raw.githubusercontent.com/Kugane/exile_lgsm/master/cronjobs.txt 2>&1 | grep -F HTTP | cut -c45- | uniq
	sleep 1
	fn_arma3config
fi