#!/bin/bash
# LGSM fn_update_dl function
# Original Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 040715

# Description: Runs a server update.

local modulename="Update"

fn_steamcmd_dl(){
fn_check_root
fn_check_systemdir
fn_details_config
fn_printdots "Updating ${servername}"
sleep 1
fn_printoknl "Updating ${servername}"
fn_scriptlog "Updating ${servername}"
sleep 1
cd "${rootdir}"
cd "steamcmd"

# Detects if unbuffer command is available.
if [ $(command -v unbuffer) ]; then
	unbuffer=unbuffer
fi
	${unbuffer} ./steamcmd.sh +login "${steamuser}" "${steampass}" +force_install_dir "${filesdir}" +app_update "${appid}" +quit|tee -a "${scriptlog}"
}
	fn_steamcmd_dl
